#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Forms.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Community.Dashboard.Forms;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Community.Dashboard.Forms.Pages;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\ManagementPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementPage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\ManagementPage.cshtml"
  
    Layout = new LayoutPage(Title);
    var version = $"v{GlobalConfigurationExtension.FileSuffix().Replace("_", ".")}";


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row hdm-management-container\">\r\n    <aside class=\"col-md-3 hdm-side" +
"bar-container\" role=\"navigation\" aria-label=\"Job Queue Navigation\">\r\n        ");


            
            #line 14 "..\..\Pages\ManagementPage.cshtml"
   Write(Html.RenderPartial(new Partials.ManagementSidebarPartial(Support.ManagementSidebarItemCollection.Items)));

            
            #line default
            #line hidden
WriteLiteral(@"
    </aside>
    <main class=""col-md-9 hdm-main-content"" role=""main"">
        <div class=""hdm-welcome-panel visible-md-block visible-lg-block"">
            <div class=""hdm-welcome-icon"">
                <span class=""glyphicon glyphicon-tasks"" aria-hidden=""true""></span>
            </div>
            <h2 class=""hdm-welcome-title"">Dashboard Forms</h2>
            <p class=""hdm-welcome-text"">
                Select a queue name from the menu on the left to see the jobs available.
            </p>
            <small class=""hdm-version-badge"">");


            
            #line 25 "..\..\Pages\ManagementPage.cshtml"
                                        Write(version);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n        </div>\r\n    </main>\r\n\r\n    ");


            
            #line 29 "..\..\Pages\ManagementPage.cshtml"
Write(Html.RenderPartial(new Partials.ClientResources()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
