#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Forms.Pages
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Pages\ManagementBasePage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Community.Dashboard.Forms;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Community.Dashboard.Forms.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Community.Dashboard.Forms.Support;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\ManagementBasePage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementBasePage : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");










            
            #line 10 "..\..\Pages\ManagementBasePage.cshtml"
  
	Layout = new LayoutPage(ManagementPage.Title);


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row hdm-management-container\">\r\n\t<aside class=\"col-md-3 hdm-sidebar" +
"-container\" role=\"navigation\" aria-label=\"Job Queue Navigation\">\r\n\t\t");


            
            #line 16 "..\..\Pages\ManagementBasePage.cshtml"
Write(Html.RenderPartial(new Partials.ManagementSidebarPartial(ManagementSidebarItemCollection.Items)));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t</aside>\r\n\t<main class=\"col-md-9 hdm-main-content\" role=\"main\">\r\n\t\t<div class=" +
"\"accordion job-panels\" role=\"region\" aria-label=\"Job Sections\">\r\n");


            
            #line 20 "..\..\Pages\ManagementBasePage.cshtml"
 			foreach (var sectionKey in jobSections.Keys)
			{
				var scrubbedSection = sectionKey.SanitizeHtmlId();
				var expanded = jobSections.Keys.First() == sectionKey;

				var headingCollapsed = expanded ? "" : "collapsed";
				var ariaExpanded = expanded ? "true" : "false";
				var panelCollapsed = expanded ? "collapse in" : "collapse";

				if (jobSections.Count > 1)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<section class=\"panel panel-success card wrapper-panel hdm-section-panel\" da" +
"ta-id=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                    Write($"section_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 31 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                      Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t<header id=\"");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
              Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-heading card-header ");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                       Write(headingCollapsed);

            
            #line default
            #line hidden
WriteLiteral("\" role=\"button\" tabindex=\"0\" data-toggle=\"collapse\" data-target=\"");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                          Write($"#section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                                                                                   Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-controls=\"");


            
            #line 32 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                                                                                                                                  Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t\t<h2 class=\"panel-title hdm-section-title\">\r\n\t\t\t\t\t\t\t\t<span class=\"glyph" +
"icon glyphicon-folder-open hdm-section-icon\" aria-hidden=\"true\"></span>\r\n\t\t\t\t\t\t\t" +
"\t");


            
            #line 35 "..\..\Pages\ManagementBasePage.cshtml"
   Write(sectionKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t<span class=\"hdm-section-badge\">");


            
            #line 36 "..\..\Pages\ManagementBasePage.cshtml"
                                   Write(jobs.Count(j => j.SectionTitle == sectionKey));

            
            #line default
            #line hidden
WriteLiteral(" jobs</span>\r\n\t\t\t\t\t\t\t</h2>\r\n\t\t\t\t\t\t</header>\r\n\t\t\t\t\t\t<div id=\"");


            
            #line 39 "..\..\Pages\ManagementBasePage.cshtml"
           Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 39 "..\..\Pages\ManagementBasePage.cshtml"
                                                                          Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 39 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                          Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 39 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                           Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" role=\"region\">\r\n\t\t\t\t\t\t\t<div class=\"hdm-section-body\">\r\n\t\t\t\t\t\t\t\t");


            
            #line 41 "..\..\Pages\ManagementBasePage.cshtml"
   Write(Html.RenderPartial(new Partials.PanelPartial(scrubbedSection, jobs.Where(j => j.SectionTitle == sectionKey).ToList())));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</section>\r\n");


            
            #line 45 "..\..\Pages\ManagementBasePage.cshtml"
				}
				else
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<section class=\"hdm-single-section\" aria-labelledby=\"");


            
            #line 48 "..\..\Pages\ManagementBasePage.cshtml"
                                                      Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t\t\t<header class=\"hdm-section-header\">\r\n\t\t\t\t\t\t\t<h1 id=\"");


            
            #line 50 "..\..\Pages\ManagementBasePage.cshtml"
           Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"page-header single-section hdm-page-title\">\r\n\t\t\t\t\t\t\t\t<span class=\"glyphi" +
"con glyphicon-folder-open hdm-section-icon\" aria-hidden=\"true\"></span>\r\n\t\t\t\t\t\t\t\t" +
"");


            
            #line 52 "..\..\Pages\ManagementBasePage.cshtml"
   Write(sectionKey);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t<span class=\"hdm-section-badge\">");


            
            #line 53 "..\..\Pages\ManagementBasePage.cshtml"
                                   Write(jobs.Count(j => j.SectionTitle == sectionKey));

            
            #line default
            #line hidden
WriteLiteral(" jobs</span>\r\n\t\t\t\t\t\t\t</h1>\r\n\t\t\t\t\t\t</header>\r\n\t\t\t\t\t\t<div id=\"");


            
            #line 56 "..\..\Pages\ManagementBasePage.cshtml"
           Write($"section_collapse_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 56 "..\..\Pages\ManagementBasePage.cshtml"
                                                                          Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral(" hdm-section-content\" aria-expanded=\"");


            
            #line 56 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                              Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 56 "..\..\Pages\ManagementBasePage.cshtml"
                                                                                                                                                               Write($"section_heading_{scrubbedSection}");

            
            #line default
            #line hidden
WriteLiteral("\" role=\"region\">\r\n\t\t\t\t\t\t\t");


            
            #line 57 "..\..\Pages\ManagementBasePage.cshtml"
  Write(Html.RenderPartial(new Partials.PanelPartial(scrubbedSection, jobs.Where(j => j.SectionTitle == sectionKey).ToList())));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</div>\r\n\t\t\t\t\t</section>\r\n");


            
            #line 60 "..\..\Pages\ManagementBasePage.cshtml"
				}
			}

            
            #line default
            #line hidden
WriteLiteral("\t\t</div>\r\n\t</main>\r\n\r\n\t");


            
            #line 65 "..\..\Pages\ManagementBasePage.cshtml"
Write(Html.RenderPartial(new Partials.ClientResources()));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
