#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Forms.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\Partials\ButtonPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\Partials\ButtonPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Pages;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Partials\ButtonPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Support;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\Partials\ButtonPartial.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\Partials\ButtonPartial.cshtml"
    using Newtonsoft.Json.Converters;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ButtonPartial : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");








            
            #line 8 "..\..\Pages\Partials\ButtonPartial.cshtml"
  
    var url = $"{ManagementPage.UrlRoute}/{Job.JobId.SanitizeHtmlId()}";
	var loadingText = "Queuing";

	var timeSpanItems = new Dictionary<string, string>() {
		{ "5 seconds", "0:0:5" },
		{ "10 seconds", "0:0:10" },
		{ "15 seconds", "0:0:15" },
		{ "30 seconds", "0:0:30" },
		{ "60 seconds", "0:1:0" }
	};

	var cronItems = new Dictionary<string, string>() {
		{ "Every Minute", Cron.Minutely() },
		{ "Hourly", Cron.Hourly() },
		{ "Daily", Cron.Daily() },
		{ "Weekly", Cron.Weekly() },
		{ "Monthly", Cron.Monthly() },
		{ "Annually", Cron.Yearly() }
	};


            
            #line default
            #line hidden
WriteLiteral(@"
<div class=""hdm-action-controls"" role=""group"" aria-label=""Job execution controls"">
	<!-- Task Type Selector -->
	<div class=""hdm-task-type-selector btn-group"">
		<button class=""btn btn-default dropdown-toggle hdm-task-type-btn"" type=""button"" id=""taskType_@JobId"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false"">
			<span class=""glyphicon glyphicon-flash"" aria-hidden=""true""></span>
			<span class=""hdm-task-type-label"">Task type:</span>
			<span class=""");


            
            #line 36 "..\..\Pages\Partials\ButtonPartial.cshtml"
           Write(JobId);

            
            #line default
            #line hidden
WriteLiteral(@" commandsType hdm-task-type-value"">Immediate</span>
			<span class=""caret""></span>
		</button>
		<ul class=""dropdown-menu hdm-task-type-menu"" aria-labelledby=""taskType_@JobId"" role=""menu"">
			<li role=""menuitem"">
				<a class=""commands-type"" data-commands-type=""Enqueue"" data-id=""");


            
            #line 41 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                              Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0)\">\r\n\t\t\t\t\t<span class=\"glyphicon glyphicon-play-circle\" " +
"aria-hidden=\"true\"></span>\r\n\t\t\t\t\tImmediate\r\n\t\t\t\t</a>\r\n\t\t\t</li>\r\n\t\t\t<li role=\"men" +
"uitem\">\r\n\t\t\t\t<a class=\"commands-type\" data-commands-type=\"ScheduleDateTime\" data" +
"-id=\"");


            
            #line 47 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                       Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0)\">\r\n\t\t\t\t\t<span class=\"glyphicon glyphicon-calendar\" ari" +
"a-hidden=\"true\"></span>\r\n\t\t\t\t\tScheduled\r\n\t\t\t\t</a>\r\n\t\t\t</li>\r\n\t\t\t<li role=\"menuit" +
"em\">\r\n\t\t\t\t<a class=\"commands-type\" data-commands-type=\"ScheduleTimeSpan\" data-id" +
"=\"");


            
            #line 53 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                       Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0)\">\r\n\t\t\t\t\t<span class=\"glyphicon glyphicon-time\" aria-hi" +
"dden=\"true\"></span>\r\n\t\t\t\t\tDelayed\r\n\t\t\t\t</a>\r\n\t\t\t</li>\r\n\t\t\t<li role=\"menuitem\">\r\n" +
"\t\t\t\t<a class=\"commands-type\" data-commands-type=\"CronExpression\" data-id=\"");


            
            #line 59 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                     Write(JobId);

            
            #line default
            #line hidden
WriteLiteral(@""" href=""javascript:void(0)"">
					<span class=""glyphicon glyphicon-repeat"" aria-hidden=""true""></span>
					Repeating
				</a>
			</li>
		</ul>
	</div>

	<!-- Immediate Command -->
	<div class=""commands-panel hdm-command-panel Enqueue"" role=""group"" aria-label=""Immediate execution"">
		<button class=""hdm-management-input-commands btn btn-success hdm-execute-btn"" data-url=""");


            
            #line 69 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                     Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 69 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                      Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral("\" input-id=\"");


            
            #line 69 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                              Write(JobId);

            
            #line default
            #line hidden
WriteLiteral(@""" input-type=""Enqueue"">
			<span class=""glyphicon glyphicon-play-circle"" aria-hidden=""true""></span>
			<span class=""hdm-btn-text"">Queue Execution</span>
		</button>
	</div>

	<!-- Schedule DateTime Command -->
	<div class=""commands-options ScheduleDateTime hdm-command-options hide"" role=""group"" aria-label=""Schedule date selection"">
		<div class=""hdm-execution-input input-group date hdm-datetime-picker"" id=""");


            
            #line 77 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                        Write($"{JobId}_datetimepicker");

            
            #line default
            #line hidden
WriteLiteral("\" data-td_options=\"");


            
            #line 77 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                      Write(JsonConvert.SerializeObject(JsonConvert.DeserializeObject(JobsHelper.ClientSideConfigurationOptions.DateTimeOpts.ScheduleButtonOptions), Formatting.None));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"Select date and time." +
"..\" id=\"");


            
            #line 78 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                 Write($"{JobId}_sys_datetime");

            
            #line default
            #line hidden
WriteLiteral(@""" />
			<span class=""input-group-addon"">
				<span class=""glyphicon glyphicon-calendar"" aria-hidden=""true""></span>
			</span>
		</div>
	</div>
	<div class=""commands-panel ScheduleDateTime hdm-command-panel hide"" role=""group"" aria-label=""Schedule execution"">
		<button class=""btn btn-primary hdm-management-input-commands hdm-execute-btn"" type=""button"" input-id=""");


            
            #line 85 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                   Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" input-type=\"ScheduleDateTime\" data-url=\"");


            
            #line 85 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                   Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 85 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                    Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral(@""">
			<span class=""glyphicon glyphicon-calendar"" aria-hidden=""true""></span>
			<span class=""hdm-btn-text"">Schedule Execution</span>
		</button>
	</div>

	<!-- Schedule Timespan Command -->
	<div class=""commands-options ScheduleTimeSpan hdm-command-options hide"" role=""group"" aria-label=""Delay duration input"">
		<input type=""text"" class=""hdm-execution-input form-control time hdm-timespan-input"" placeholder=""HH:mm:ss"" id=""");


            
            #line 93 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                             Write($"{JobId}_sys_timespan");

            
            #line default
            #line hidden
WriteLiteral(@""" data-inputmask=""'mask' :'99:99:99'"" aria-label=""Delay duration in hours, minutes, seconds"">
	</div>
	<div class=""commands-panel ScheduleTimeSpan hdm-command-panel hide"" role=""group"" aria-label=""Delayed execution"">
		<div class=""btn-group hdm-split-btn"">
			<button class=""btn btn-info hdm-management-input-commands hdm-execute-btn"" type=""button"" input-id=""");


            
            #line 97 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                 Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" input-type=\"ScheduleTimeSpan\" data-url=\"");


            
            #line 97 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                 Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 97 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                  Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral(@""">
				<span class=""glyphicon glyphicon-time"" aria-hidden=""true""></span>
				<span class=""hdm-btn-text"">Delayed Execution</span>
			</button>
			<button type=""button"" class=""btn btn-info dropdown-toggle hdm-split-toggle"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false"" aria-label=""Quick delay options"">
				<span class=""caret""></span>
			</button>
			<ul class=""dropdown-menu dropdown-menu-right hdm-quick-options"" role=""menu"">
");


            
            #line 105 "..\..\Pages\Partials\ButtonPartial.cshtml"
 				foreach (var o in timeSpanItems)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<li role=\"menuitem\">\r\n\t\t\t\t\t\t<a class=\"hdm-management-input-commands\" input-i" +
"d=\"");


            
            #line 108 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                    Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" input-type=\"ScheduleTimeSpan\" data-schedule=\"");


            
            #line 108 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                         Write(o.Value);

            
            #line default
            #line hidden
WriteLiteral("\" data-url=\"");


            
            #line 108 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                             Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 108 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                              Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0)\">\r\n\t\t\t\t\t\t\t<span class=\"glyphicon glyphicon-time\" aria-" +
"hidden=\"true\"></span>\r\n\t\t\t\t\t\t\t");


            
            #line 110 "..\..\Pages\Partials\ButtonPartial.cshtml"
  Write(o.Key);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t</a>\r\n\t\t\t\t\t</li>\r\n");


            
            #line 113 "..\..\Pages\Partials\ButtonPartial.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral(@"			</ul>
		</div>
	</div>

	<!-- Cron Expression Command -->
	<div class=""commands-options CronExpression hdm-command-options hide"" role=""group"" aria-label=""Cron expression input"">
		<input class=""form-control hdm-execution-input-exp hdm-cron-input"" title=""Enter a cron expression"" id=""");


            
            #line 120 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                     Write($"{JobId}_sys_cron");

            
            #line default
            #line hidden
WriteLiteral("\" placeholder=\"* * * * * (min hr day mon wkday)\" value=\"\" />\r\n\t</div>\r\n");


            
            #line 122 "..\..\Pages\Partials\ButtonPartial.cshtml"
 	if (Job.AllowMultiple)
	{

            
            #line default
            #line hidden
WriteLiteral("\t\t<div class=\"commands-options CronExpression hdm-command-options hdm-job-name-op" +
"tion hide\" role=\"group\" aria-label=\"Job name input\">\r\n\t\t\t<div class=\"input-group" +
" hdm-job-name-group\" id=\"");


            
            #line 125 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                               Write($"{JobId}_Name");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n\t\t\t\t<input type=\"text\" class=\"hdm-execution-input-name form-control\" placehol" +
"der=\"Unique Job Name\" id=\"");


            
            #line 126 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                   Write($"{JobId}_sys_name");

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Give a unique name to your job\" spellcheck=\"false\">\r\n\t\t\t</div>\r\n\t\t</div>" +
"\r\n");


            
            #line 129 "..\..\Pages\Partials\ButtonPartial.cshtml"
	}

            
            #line default
            #line hidden
WriteLiteral(@"	<div class=""commands-panel CronExpression hdm-command-panel hide"" role=""group"" aria-label=""Recurring execution"">
		<div class=""btn-group hdm-split-btn"">
			<button class=""btn btn-warning hdm-management-input-commands hdm-execute-btn"" type=""button"" input-id=""");


            
            #line 132 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                    Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" input-type=\"CronExpression\" data-confirm=\"If this job already has a schedule th" +
"en it will be updated. Continue?\" data-url=\"");


            
            #line 132 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                                                                       Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 132 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                                                                                                        Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral(@""">
				<span class=""glyphicon glyphicon-repeat"" aria-hidden=""true""></span>
				<span class=""hdm-btn-text"">Recurring Execution</span>
			</button>
			<button type=""button"" class=""btn btn-warning dropdown-toggle hdm-split-toggle"" data-toggle=""dropdown"" aria-haspopup=""true"" aria-expanded=""false"" aria-label=""Quick cron options"">
				<span class=""caret""></span>
			</button>
			<ul class=""dropdown-menu dropdown-menu-right hdm-quick-options"" role=""menu"">
");


            
            #line 140 "..\..\Pages\Partials\ButtonPartial.cshtml"
 				foreach (var o in cronItems)
				{

            
            #line default
            #line hidden
WriteLiteral("\t\t\t\t\t<li role=\"menuitem\">\r\n\t\t\t\t\t\t<a class=\"hdm-management-input-commands\" input-i" +
"d=\"");


            
            #line 143 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                    Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\" input-type=\"CronExpression\" data-schedule=\"");


            
            #line 143 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                       Write(o.Value);

            
            #line default
            #line hidden
WriteLiteral("\" data-confirm=\"If this job already has a schedule then it will be updated. Conti" +
"nue?\" data-url=\"");


            
            #line 143 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                                                Write(Url.To(url));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 143 "..\..\Pages\Partials\ButtonPartial.cshtml"
                                                                                                                                                                                                                                                 Write(loadingText);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"javascript:void(0)\">\r\n\t\t\t\t\t\t\t<span class=\"hdm-cron-label\">");


            
            #line 144 "..\..\Pages\Partials\ButtonPartial.cshtml"
                               Write(o.Key);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n\t\t\t\t\t\t\t<code class=\"hdm-cron-value\">");


            
            #line 145 "..\..\Pages\Partials\ButtonPartial.cshtml"
                               Write(o.Value);

            
            #line default
            #line hidden
WriteLiteral("</code>\r\n\t\t\t\t\t\t</a>\r\n\t\t\t\t\t</li>\r\n");


            
            #line 148 "..\..\Pages\Partials\ButtonPartial.cshtml"
				}

            
            #line default
            #line hidden
WriteLiteral("\t\t\t</ul>\r\n\t\t</div>\r\n\t</div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
