#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Forms.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms;
    
    #line default
    #line hidden
    
    #line 2 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ManagementSidebarPartial : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
  


            
            #line default
            #line hidden
WriteLiteral("\r\n<nav class=\"hdm-sidebar-nav\" aria-label=\"Job Queues\">\r\n    <!-- Mobile Navigati" +
"on -->\r\n    <ul class=\"nav nav-tabs hdm-mobile-nav hidden-md hidden-lg\" role=\"ta" +
"blist\">\r\n");


            
            #line 12 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
         foreach (var item in Items)
        {
            var itemValue = item(this);
            var activeClass = itemValue.Active ? "active" : "";
            var ariaCurrent = itemValue.Active ? "page" : null;

            
            #line default
            #line hidden
WriteLiteral("            <li role=\"presentation\" class=\"");


            
            #line 17 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                      Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <a href=\"");


            
            #line 18 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                    Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 18 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                     Write(ariaCurrent != null ? $"aria-current=\"{ariaCurrent}\"" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    <span class=\"hdm-nav-text\">");


            
            #line 19 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                          Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n            </li>\r\n");


            
            #line 22 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n\r\n    <!-- Desktop Navigation -->\r\n    <ul class=\"nav nav-pills nav-st" +
"acked hdm-desktop-nav visible-md-block visible-lg-block\" role=\"navigation\">\r\n");


            
            #line 27 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
         foreach (var item in Items)
        {
            var itemValue = item(this);
            var activeClass = itemValue.Active ? "active" : "";
            var ariaCurrent = itemValue.Active ? "page" : null;

            
            #line default
            #line hidden
WriteLiteral("            <li role=\"presentation\" class=\"");


            
            #line 32 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                      Write(activeClass);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <a href=\"");


            
            #line 33 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                    Write(itemValue.Url);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 33 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                     Write(ariaCurrent != null ? $"aria-current=\"{ariaCurrent}\"" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                    <span class=\"glyphicon glyphicon-folder-open hdm-nav-icon\"" +
" aria-hidden=\"true\"></span>\r\n                    <span class=\"hdm-nav-text\">");


            
            #line 35 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
                                          Write(itemValue.Text);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </a>\r\n            </li>\r\n");


            
            #line 38 "..\..\Pages\Partials\ManagementSidebarPartial.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n</nav>\r\n");


        }
    }
}
#pragma warning restore 1591
