#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Community.Dashboard.Forms.Pages.Partials
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Pages\Partials\PanelPartial.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Metadata;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Pages;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Pages.Partials;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Community.Dashboard.Forms.Support;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.Server;
    
    #line default
    #line hidden
    
    #line 12 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    #line 13 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Newtonsoft.Json;
    
    #line default
    #line hidden
    
    #line 14 "..\..\Pages\Partials\PanelPartial.cshtml"
    using Newtonsoft.Json.Linq;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class PanelPartial : Hangfire.Dashboard.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");
















            
            #line 16 "..\..\Pages\Partials\PanelPartial.cshtml"
  



            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 20 "..\..\Pages\Partials\PanelPartial.cshtml"
 foreach (var job in Jobs)
{
    var id = $"{SectionName}_{job.MethodName.SanitizeHtmlId()}";
    var expanded = Jobs.First() == job;

    var options = new JObject();
    var qAttr = job.MethodInfo.GetCustomAttributes(true).OfType<QueueAttribute>().FirstOrDefault();
    var queueName = (qAttr == default ? "default" : qAttr.Queue).ToUpper();
    options.Add("Queue", queueName);

    var showMDAttr = job.MethodInfo.GetCustomAttributes(true).OfType<ShowMetaDataAttribute>().FirstOrDefault();
    var showMeta = showMDAttr != default && showMDAttr.ShowOnUI;

    if (showMeta)
    {
        var retryAttr = job.MethodInfo.GetCustomAttributes(true).OfType<AutomaticRetryAttribute>().FirstOrDefault();
        if (retryAttr != default)
        {
            var ar = new JObject(){
                            { "Attempts", retryAttr.Attempts },
                            { "AllowMultiple", retryAttr.AllowMultiple },
                            { "DelaysInSeconds", (retryAttr.DelaysInSeconds != null ? JsonConvert.SerializeObject(retryAttr.DelaysInSeconds) : null) },
                            { "LogEvents", retryAttr.LogEvents },
                            { "OnAttemptsExceeded", (retryAttr.OnAttemptsExceeded == AttemptsExceededAction.Delete ? "Delete" : "Fail") }
                        };
            options.Add("AutomaticRetryAttribute", ar);
        }
    }
    var headingCollapsed = expanded ? "" : "collapsed";
    var panelCollapsed = expanded ? "collapse in" : "collapse";
    var ariaExpanded = expanded ? "true" : "false";
    var multiAllowed = job.AllowMultiple ? "hdm-multi-allowed" : "";
    var hasHistory = JobsHistory.ContainsKey(job.MethodName) && JobsHistory[job.MethodName].Any();


            
            #line default
            #line hidden
WriteLiteral("    <article class=\"panel panel-info hdm-management hdm-job-panel card ");


            
            #line 54 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                  Write(multiAllowed);

            
            #line default
            #line hidden
WriteLiteral("\" data-id=\"");


            
            #line 54 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                          Write(id);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 54 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                 Write($"heading_{id}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <header id=\"");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
                Write($"heading_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-heading card-header ");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                    Write(headingCollapsed);

            
            #line default
            #line hidden
WriteLiteral("\" role=\"button\" tabindex=\"0\" data-toggle=\"collapse\" data-target=\"");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                       Write($"#collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" aria-expanded=\"");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                                                           Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-controls=\"");


            
            #line 55 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                                                                                          Write($"collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <h3 class=\"panel-title hdm-job-title\">\r\n                <span cla" +
"ss=\"glyphicon glyphicon-cog hdm-job-icon\" aria-hidden=\"true\"></span>\r\n          " +
"      <span class=\"hdm-job-name\">");


            
            #line 58 "..\..\Pages\Partials\PanelPartial.cshtml"
                                      Write(job.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                <span class=\"hdm-queue-badge\" title=\"Queue: ");


            
            #line 59 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                       Write(queueName);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 59 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                   Write(queueName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 60 "..\..\Pages\Partials\PanelPartial.cshtml"
                 if (job.AllowMultiple)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <span class=\"hdm-multi-badge\" title=\"Multiple instances allow" +
"ed\">\r\n                        <span class=\"glyphicon glyphicon-duplicate\" aria-h" +
"idden=\"true\"></span>\r\n                    </span>\r\n");


            
            #line 65 "..\..\Pages\Partials\PanelPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </h3>\r\n        </header>\r\n        <div id=\"");


            
            #line 68 "..\..\Pages\Partials\PanelPartial.cshtml"
             Write($"collapse_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" class=\"panel-collapse ");


            
            #line 68 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                       Write(panelCollapsed);

            
            #line default
            #line hidden
WriteLiteral(" hdm-job-container\" aria-expanded=\"");


            
            #line 68 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                         Write(ariaExpanded);

            
            #line default
            #line hidden
WriteLiteral("\" aria-labelledby=\"");


            
            #line 68 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                          Write($"heading_{id}");

            
            #line default
            #line hidden
WriteLiteral("\" role=\"region\">\r\n            <!-- Job Description Section -->\r\n            <div " +
"class=\"panel-body hdm-job-description-section\">\r\n");


            
            #line 71 "..\..\Pages\Partials\PanelPartial.cshtml"
                 if (!string.IsNullOrWhiteSpace(job.Description))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <p class=\"hdm-job-description\">\r\n                        <spa" +
"n class=\"glyphicon glyphicon-info-sign hdm-description-icon\" aria-hidden=\"true\">" +
"</span>\r\n                        ");


            
            #line 75 "..\..\Pages\Partials\PanelPartial.cshtml"
                   Write(job.Description);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n");


            
            #line 77 "..\..\Pages\Partials\PanelPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                \r\n");


            
            #line 79 "..\..\Pages\Partials\PanelPartial.cshtml"
                 if (showMeta)
                {

            
            #line default
            #line hidden
WriteLiteral(@"                    <details class=""hdm-metadata-details"">
                        <summary class=""hdm-metadata-summary"">
                            <span class=""glyphicon glyphicon-list-alt"" aria-hidden=""true""></span>
                            View Job Metadata
                        </summary>
                        <div class=""hdm-metadata-content"">
                            <pre class=""hdm-metadata-pre""><code>");


            
            #line 87 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                           Write(JsonConvert.SerializeObject(options, Formatting.Indented));

            
            #line default
            #line hidden
WriteLiteral("</code></pre>\r\n                        </div>\r\n                    </details>\r\n");


            
            #line 90 "..\..\Pages\Partials\PanelPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                \r\n                <!-- Job History Dropdown -->\r\n");


            
            #line 93 "..\..\Pages\Partials\PanelPartial.cshtml"
                 if (hasHistory)
                {

            
            #line default
            #line hidden
WriteLiteral(@"                    <fieldset class=""hdm-history-fieldset"">
                        <legend class=""hdm-history-legend"">
                            <span class=""glyphicon glyphicon-time"" aria-hidden=""true""></span>
                            Load Previous Arguments
                        </legend>
                        <div class=""input-group hdm-history-group"">
                            <label for=""history-");


            
            #line 101 "..\..\Pages\Partials\PanelPartial.cshtml"
                                           Write(id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"sr-only\">Select a previous job execution</label>\r\n                      " +
"      <select class=\"form-control job-history-dropdown hdm-history-select\" id=\"h" +
"istory-");


            
            #line 102 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                        Write(id);

            
            #line default
            #line hidden
WriteLiteral("\" data-jobtype=\"");


            
            #line 102 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                           Write(id);

            
            #line default
            #line hidden
WriteLiteral("\" aria-describedby=\"history-help-");


            
            #line 102 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                                                                                                                               Write(id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <option value=\"\" selected disabled>Select a p" +
"revious execution...</option>\r\n                                <option value=\"Re" +
"set\" data-optionvalue=\"\">Reset to defaults</option>\r\n");


            
            #line 105 "..\..\Pages\Partials\PanelPartial.cshtml"
                                 foreach (var jobHistory in JobsHistory[job.MethodName])
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <option value=\"");


            
            #line 107 "..\..\Pages\Partials\PanelPartial.cshtml"
                                              Write(jobHistory.Id);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                            data-optiontext=\"");


            
            #line 108 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                        Write(jobHistory.Time);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                                            data-optionvalue=\"");


            
            #line 109 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                         Write(jobHistory.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                        ");


            
            #line 110 "..\..\Pages\Partials\PanelPartial.cshtml"
                                   Write(jobHistory.Type);

            
            #line default
            #line hidden
WriteLiteral(" — ");


            
            #line 110 "..\..\Pages\Partials\PanelPartial.cshtml"
                                                      Write(jobHistory.Time);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </option>\r\n");


            
            #line 112 "..\..\Pages\Partials\PanelPartial.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral(@"                            </select>
                            <span class=""input-group-btn"">
                                <button type=""button"" class=""btn btn-default load-history-btn"" aria-label=""Load selected job arguments"">
                                    <span class=""glyphicon glyphicon-download-alt"" aria-hidden=""true""></span>
                                    Load
                                </button>
                            </span>
                        </div>
                        <small id=""history-help-");


            
            #line 121 "..\..\Pages\Partials\PanelPartial.cshtml"
                                           Write(id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"hdm-history-help form-text text-muted\">\r\n                            Sel" +
"ect a previous execution to load its arguments into the form below.\r\n           " +
"             </small>\r\n                    </fieldset>\r\n");


            
            #line 125 "..\..\Pages\Partials\PanelPartial.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n            \r\n            <!-- Job Form Section -->\r\n        " +
"    <div class=\"panel-body hdm-job-form-section\">\r\n                ");


            
            #line 130 "..\..\Pages\Partials\PanelPartial.cshtml"
           Write(Html.RenderPartial(new JobPartial(id, job, hasHistory ? JobsHistory[job.MethodName] : new System.Collections.Generic.List<JobHistoryMetadata>())));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            \r\n            <!-- Job Actions Footer -->\r\n    " +
"        <footer class=\"panel-footer hdm-job-actions\">\r\n                ");


            
            #line 135 "..\..\Pages\Partials\PanelPartial.cshtml"
           Write(Html.RenderPartial(new ButtonPartial(id, job)));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </footer>\r\n        </div>\r\n    </article>\r\n");


            
            #line 139 "..\..\Pages\Partials\PanelPartial.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
